name: ESLint

on:
  push:
    branches: ["*"]  # This will trigger the workflow for all branches
  pull_request:
    branches: ["*"]  # This will trigger the workflow for PRs on any branch

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # Only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # This will install all dependencies, including eslint

      - name: Run linting
        run: npm run lint  # This will run the linting script from package.json
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true